CREATE OR REPLACE WAREHOUSE SECURITY_WH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

CREATE OR REPLACE DATABASE SECURITY_DEMO_DB;

CREATE OR REPLACE SCHEMA SECURITY_DEMO_DB.HR;

CREATE OR REPLACE TABLE SECURITY_DEMO_DB.HR.EMPLOYEES
(
    EMP_ID NUMBER,
    NAME VARCHAR,
    DEPARTMENT VARCHAR,
    EMAIL VARCHAR,
    SSN VARCHAR,
    SALARY NUMBER
);

INSERT INTO SECURITY_DEMO_DB.HR.EMPLOYEES VALUES
(101,'John Smith','IT','john@gmail.com','123-45-6789',80000),
(102,'Emma Brown','HR','emma@gmail.com','234-56-7890',75000),
(103,'David Lee','Finance','david@gmail.com','345-67-8901',90000),
(104,'Sophia Wilson','IT','sophia@gmail.com','456-78-9012',85000),
(105,'James Miller','Sales','james@gmail.com','567-89-0123',70000);

CREATE OR REPLACE ROLE HR_ROLE;
CREATE OR REPLACE ROLE ANALYST_ROLE;
CREATE OR REPLACE ROLE ENGINEER_ROLE;
CREATE OR REPLACE ROLE DATA_STEWARD_ROLE;


GRANT USAGE
ON WAREHOUSE SECURITY_WH
TO ROLE HR_ROLE;


GRANT USAGE
ON WAREHOUSE SECURITY_WH
TO ROLE ANALYST_ROLE;


GRANT USAGE
ON WAREHOUSE SECURITY_WH
TO ROLE ENGINEER_ROLE;


GRANT USAGE
ON WAREHOUSE SECURITY_WH
TO ROLE DATA_STEWARD_ROLE;

--DATABASE ACCESS
GRANT USAGE
ON DATABASE SECURITY_DEMO_DB
TO ROLE HR_ROLE;

GRANT USAGE
ON DATABASE SECURITY_DEMO_DB
TO ROLE ANALYST_ROLE;

GRANT USAGE
ON DATABASE SECURITY_DEMO_DB
TO ROLE ENGINEER_ROLE;

GRANT USAGE
ON DATABASE SECURITY_DEMO_DB
TO ROLE DATA_STEWARD_ROLE;


--SCHEMA LEVEL ACCESS
GRANT USAGE
ON SCHEMA SECURITY_DEMO_DB.HR
TO ROLE HR_ROLE;

GRANT USAGE
ON SCHEMA SECURITY_DEMO_DB.HR
TO ROLE ANALYST_ROLE;

GRANT USAGE
ON SCHEMA SECURITY_DEMO_DB.HR
TO ROLE ENGINEER_ROLE;

GRANT USAGE
ON SCHEMA SECURITY_DEMO_DB.HR
TO ROLE DATA_STEWARD_ROLE;


-- TABLE PERMISSIONS
GRANT SELECT
ON TABLE SECURITY_DEMO_DB.HR.EMPLOYEES
TO ROLE HR_ROLE;

GRANT SELECT
ON TABLE SECURITY_DEMO_DB.HR.EMPLOYEES
TO ROLE ANALYST_ROLE;



GRANT SELECT,INSERT,UPDATE,DELETE
ON TABLE SECURITY_DEMO_DB.HR.EMPLOYEES
TO ROLE ENGINEER_ROLE;

GRANT SELECT
ON TABLE SECURITY_DEMO_DB.HR.EMPLOYEES
TO ROLE DATA_STEWARD_ROLE;

SELECT CURRENT_USER();

CREATE OR REPLACE USER  GEETHA
PASSWORD='Geetha@demo2026!'
LOGIN_NAME='GEETHA',
DISPLAY_NAME='Geetha'
DEFAULT_ROLE=ENGINEER_ROLE,
DEFAULT_WAREHOUSE=SECURITY_WH,
DEFAULT_NAMESPACE='SECURIT_DEMO_DB.HR'
MUST_CHANGE_PASSWORD=FALSE;

CREATE OR REPLACE USER  JHON
PASSWORD='Jhon@demo2026!'
LOGIN_NAME='JHON',
DISPLAY_NAME='Jhon'
DEFAULT_ROLE=HR_ROLE,
DEFAULT_WAREHOUSE=SECURITY_WH,
DEFAULT_NAMESPACE='SECURIT_DEMO_DB.HR'
MUST_CHANGE_PASSWORD=FALSE;

CREATE OR REPLACE USER  PAM
PASSWORD='Pam@demo2026!'
LOGIN_NAME='PAM',
DISPLAY_NAME='Pam'
DEFAULT_ROLE=DATA_STEWARD_ROLE,
DEFAULT_WAREHOUSE=SECURITY_WH,
DEFAULT_NAMESPACE='SECURIT_DEMO_DB.HR'
MUST_CHANGE_PASSWORD=FALSE;

CREATE OR REPLACE USER  FRANSY
PASSWORD='Fransy@demo2026!'
LOGIN_NAME='FRANSY',
DISPLAY_NAME='Fransy'
DEFAULT_ROLE=ANALYST_ROLE,
DEFAULT_WAREHOUSE=SECURITY_WH,
DEFAULT_NAMESPACE='SECURIT_DEMO_DB.HR'
MUST_CHANGE_PASSWORD=FALSE;




GRANT ROLE ENGINEER_ROLE
TO USER GEETHA;

GRANT ROLE HR_ROLE
TO USER JHON;

GRANT ROLE DATA_STEWARD_ROLE
TO USER PAM;

GRANT ROLE ANALYST_ROLE
TO USER FRANSY;


SHOW GRANTS TO USER GEETHA;
SHOW GRANTS TO USER JHON;
SHOW GRANTS TO USER PAM;
SHOW GRANTS TO USER FRANSY;

SHOW GRANTS TO ROLE ENGINEER_ROLE;


select * from security_demo_db.hr.employees;

ALTER MASKING POLICY MASK_EMAIL
SET BODY ->
CASE
    WHEN CURRENT_ROLE() = 'HR_ROLE'
        THEN VAL
    ELSE 'MASKED@EMAIL.COM'
END;

ALTER TABLE SECURITY_DEMO_DB.HR.EMPLOYEES
MODIFY COLUMN EMAIL
SET MASKING POLICY MASK_EMAIL;


SELECT * FROM SECURITY_DEMO_DB.HR.EMPLOYEES;


--AAD CLASSIFICATION TAG
CREATE OR REPLACE TAG DATA_CLASSIFICATION
ALLOWED_VALUES
'PUBLIC',
'INTERNAL',
'PII',
'SENSITIVE PII',
'CONFIDENTIAL';

ALTER TABLE SECURITY_DEMO_DB.HR.EMPLOYEES
MODIFY COLUMN EMAIL
SET TAG DATA_CLASSIFICATION='PII';

ALTER TABLE SECURITY_DEMO_DB.HR.EMPLOYEES
MODIFY COLUMN SSN
SET TAG DATA_CLASSIFICATION='SENSITIVE PII';

ALTER TABLE SECURITY_DEMO_DB.HR.EMPLOYEES
MODIFY COLUMN SALARY
SET TAG DATA_CLASSIFICATION='CONFIDENTIAL';


hIPAA